### ISSUE TITLE
discord code where?

### ISSUE THREAD

**Issue by ArjixWasTaken** [brahmkshatriya/echo-discord#1]
[![image](https://github.com/brahmkshatriya/echo-discord/assets/53124886/6dfcb1a3-fa81-42f4-b97b-a21ca8555c63)](https://www.youtube.com/watch?v=E26gRrco8-s)

**Comment by brahmkshatriya** [comment]
https://github.com/brahmkshatriya/echo-discord/blob/main/app/src/main/java/dev/brahmkshatriya/echo/extension/RPC.kt
